apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: apps
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 9
  template:
    metadata:
      name: apps
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx