apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demi 
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 5
  template:
    metadata:
      name: demi
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx